# Configuración para Dockploy con Nixpacks
# Si quieres usar Dockerfile, renombra este archivo o elimínalo
# Dockploy usará nixpacks.toml automáticamente si este archivo no especifica dockerfile

deploy:
  port: 3000
  # El comando de inicio está en nixpacks.toml [start]
  env:
    - NODE_ENV=production


