# Configuración para Dockploy - Usando Dockerfile
# Dockerfile está funcionando correctamente (verificado localmente)

build:
  dockerfile: Dockerfile
  context: .
  # No especificar build command - Dockploy lo manejará automáticamente

deploy:
  port: 3000
  # El comando de inicio está en el Dockerfile (CMD)
  # No especificar start command aquí
  env:
    - NODE_ENV=production


